import mysql.connector
from mysql.connector import Error
# from data import category

#pp.config['MYSQL_DATABASE_HOST'] = 'http://35.183.87.173/phpMyAdmin'
#app.config['MYSQL_DATABASE_USER'] = 'yeraj'
#app.config['MYSQL_DATABASE_PASSWORD'] = 'madskills!'
#app.config['MYSQL_DATABASE_DB'] = 'Skills_Assessment_DB'

# host='localhost'
# database='Skills_Assessment_DB'
# user='yeraj'
# password='madskills!'
host='52.60.98.175'
database='ITS_SKILLS_AX'
user='yeraj'
password='madskills!'





